[package]
name = "atto-ui-markdown"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
atto-ui = { path = "../.." }
crossterm = "0.29.0"
parking_lot = "0.12.5"
pulldown-cmark = "0.13.0"
ratatui = "0.30.0"
syntect = { version = "5.3", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"

[dev-dependencies]
atto-ui-test-host = { path = "../atto-ui-test-host" }
