[package]
name = "atto-ui-node"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.4.0", features = ["serde-json"] }
napi-derive = "3.3.0"
atto-ui = { path = "../.." }
atto-ui-components = { path = "../atto-ui-components" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[build-dependencies]
napi-build = "2.2.4"
