/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Node binding wrapper around the runtime `atto_ui::app::AppHost`. */
export declare class AppHost {
  /** Create an AppHost. By default `step()` is non-blocking (`tickRate = 0`). */
  constructor(config?: AppHostConfig | undefined | null)
  /** Add a dynamic runtime window and return its opaque string handle. */
  addDynamicWindow(title: string, rect: Rect | [number, number, number, number], root: any): string
  /** Apply one TreeOp object or an array of TreeOp objects to a dynamic window. */
  applyTreeOps(windowId: string, ops: any): boolean
  /** Advance the host by one frame. Returns false when the host requests exit. */
  step(): boolean
  /** Restore terminal state for real-terminal hosts. Idempotent and a no-op for headless hosts. */
  dispose(): void
  /** Drain queued UI callback invocations. */
  drainCallbacks(): any
  /** Allocate a callback id handle for use in component event props. */
  allocCallback(): string
  /** Release a callback id handle after its component event binding is removed. */
  releaseCallback(callbackId: string): boolean
  /** Send an input event directly to one window. */
  sendEvent(windowId: string, event: any): any
  /** Close a window and invalidate its handle when successful. */
  closeWindow(windowId: string): boolean
  /**
   * Minimize a window by handle. Patches the baseline so the change is not
   * echoed back through `drain_window_events`.
   */
  minimizeWindow(windowId: string): boolean
  /** Restore a minimized window by handle. */
  restoreWindow(windowId: string): boolean
  /** Toggle maximize for a window by handle. Returns true when the state changed. */
  maximizeWindow(windowId: string): boolean
  /**
   * Drain window lifecycle events (close/minimize/maximize/restore) that
   * originated from user interaction inside the TUI. Returns `[]` when nothing
   * changed. Events are derived by diffing the current window list against the
   * baseline; JS-initiated mutations patch the baseline and so never appear here.
   */
  drainWindowEvents(): any
  /** Focus a window by handle. */
  focusWindow(windowId: string): boolean
  /** Move a window to an absolute work-area position. */
  moveWindow(windowId: string, x: number, y: number): boolean
  /** Resize a window. */
  resizeWindow(windowId: string, width: number, height: number): boolean
  /** List known windows using opaque string handles. */
  listWindows(): any
  /** Set a window title. */
  setTitle(windowId: string, title: string): boolean
  /** Replace the desktop menu bar from a JavaScript menu spec. */
  setMenuBar(spec: any): void
  /** Replace or clear custom desktop status bar text. */
  setStatusBar(left?: string | undefined | null, right?: string | undefined | null): void
  /** Set a component property by component id. */
  setProperty(id: string, name: string, value: any): void
  /** Read a component property by component id. */
  getProperty(id: string, name: string): any
  /** Export a deterministic snapshot of the desktop tree. */
  snapshot(): any
  /** Set the active theme to `dark`, `light`, or `turbo`. */
  setTheme(name: string): void
  /** Load a theme from disk, using `base` (`dark`, `light`, or `turbo`) as fallback. */
  loadTheme(path: string, base?: string | undefined | null): void
  /** Return registered runtime component schemas. */
  schemas(): any
}

/** Configuration for `new AppHost(...)`. */
export interface AppHostConfig {
  /** Headless hosts use an in-memory terminal and never touch the real TTY. */
  headless?: boolean
  /** Headless terminal width. Defaults to 80. */
  cols?: number
  /** Headless terminal height. Defaults to 24. */
  rows?: number
  /** Crossterm polling interval in milliseconds. Defaults to 0 for non-blocking `step()`. */
  tickRate?: number
  /** Enable terminal mouse capture. Defaults to true. */
  mouseCapture?: boolean
  /** Hide the terminal cursor while the host is active. Defaults to true. */
  hideCursor?: boolean
  /** Enable bracketed paste in real-terminal mode. Defaults to false. */
  bracketedPaste?: boolean
  /** Enable keyboard enhancement flags in real-terminal mode. Defaults to true. */
  keyboardEnhancement?: boolean
}

/** JavaScript-facing rectangle used by window construction. */
export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

/** Register optional runtime components from workspace companion crates. */
export declare function registerAllRuntimeComponents(): void

/** Return the native package version exposed to JavaScript smoke tests. */
export declare function version(): string
