[package]
name = "atto-ui-file-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
atto-ui = { path = "../.." }
crossterm = "0.29.0"
parking_lot = "0.12.5"
ratatui = "0.30.0"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"

[dev-dependencies]
atto-ui-test-host = { path = "../atto-ui-test-host" }

[[bin]]
name = "snapshot_file_tree_app"
path = "src/bin/snapshot_file_tree_app.rs"
test = false
