from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union

from . import _native

AppHost = _native.AppHost

RectLike = Union[Tuple[int, int, int, int], List[int], Dict[str, int]]
PaddingLike = Union[int, List[int], Tuple[int, int, int, int], Dict[str, int]]
SizeLike = Union[str, int, Dict[str, int]]
Callback = Callable[["Event", Optional["ComponentRef"]], None]

class Event:
    callback_id: int
    event: str
    target_id: Optional[str]
    payload: Any
    def __init__(self, callback_id: int, event: str, target_id: Optional[str], payload: Any) -> None: ...

class ComponentRef:
    app: App
    window: Window
    cid: str
    def __init__(self, app: App, window: Window, cid: str) -> None: ...
    def set_prop(self, name: str, value: Any) -> None: ...
    def get_prop(self, name: str) -> Any: ...
    def bind_event(self, event: str, callback: Callback) -> int: ...
    def __getattr__(self, name: str) -> Any: ...

class Component:
    type_name: str
    cid: Optional[str]
    props: Dict[str, Any]
    children: List[Component]
    events: Dict[str, Union[int, Callback]]
    layout: Optional[Dict[str, Any]]
    meta: Optional[Dict[str, Any]]
    def __init__(
        self,
        type_name: str,
        *,
        cid: Optional[str] = ...,
        props: Optional[Dict[str, Any]] = ...,
        children: Optional[Sequence[Component]] = ...,
        events: Optional[Dict[str, Union[int, Callback]]] = ...,
        layout: Optional[Dict[str, Any]] = ...,
        meta: Optional[Dict[str, Any]] = ...,
    ) -> None: ...
    def with_layout(
        self,
        *,
        width: Optional[SizeLike] = ...,
        height: Optional[SizeLike] = ...,
        margin: Optional[PaddingLike] = ...,
        align_x: Optional[str] = ...,
        align_y: Optional[str] = ...,
        anchor: Optional[Dict[str, Any]] = ...,
        tab_index: Optional[int] = ...,
    ) -> Component: ...
    def with_meta(self, **meta: Any) -> Component: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_child_dict(self) -> Dict[str, Any]: ...
    def to_spec(self, app: App) -> Dict[str, Any]: ...
    def to_child_spec(self, app: App) -> Dict[str, Any]: ...
    def collect_ids(self) -> List[str]: ...
    def collect_id_types(self) -> Dict[str, str]: ...
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Component: ...

class Window:
    app: App
    id: int
    title: str
    rect: RectLike
    content: Component
    elements: Dict[str, ComponentRef]
    def __init__(self, app: App, window_id: int, title: str, rect: RectLike, content: Component) -> None: ...
    def send_event(self, event: Dict[str, Any]) -> Dict[str, Any]: ...
    def click(self, column: int, row: int, *, button: str = ..., modifiers: Optional[Sequence[str]] = ...) -> Dict[str, Any]: ...
    def key(self, key: str, *, modifiers: Optional[Sequence[str]] = ...) -> Dict[str, Any]: ...
    def paste(self, text: str) -> Dict[str, Any]: ...
    def focus(self) -> bool: ...
    def close(self) -> bool: ...
    def move(self, x: int, y: int) -> bool: ...
    def resize(self, width: int, height: int) -> bool: ...
    def set_title(self, title: str) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @classmethod
    def from_dict(cls, app: App, data: Dict[str, Any]) -> Window: ...

class App:
    def __init__(self, *, headless: bool = ..., cols: int = ..., rows: int = ...) -> None: ...
    def register_callback(self, callback: Callback, callback_id: Optional[int] = ...) -> int: ...
    def add_dynamic_window(self, title: str, content: Union[Component, Dict[str, Any]], rect: RectLike = ...) -> Window: ...
    def step(self) -> bool: ...
    def run(self) -> None: ...
    def send_event(self, window: Union[Window, int], event: Union[str, Dict[str, Any]]) -> Dict[str, Any]: ...
    def click(self, window: Union[Window, int], column: int, row: int, *, button: str = ..., modifiers: Optional[Sequence[str]] = ...) -> Dict[str, Any]: ...
    def key(self, window: Union[Window, int], key: str, *, modifiers: Optional[Sequence[str]] = ...) -> Dict[str, Any]: ...
    def char(self, window: Union[Window, int], char: str, *, modifiers: Optional[Sequence[str]] = ...) -> Dict[str, Any]: ...
    def paste(self, window: Union[Window, int], text: str) -> Dict[str, Any]: ...
    def snapshot(self) -> Dict[str, Any]: ...
    def schemas(self) -> List[Dict[str, Any]]: ...
    def set_theme(self, name: str) -> None: ...
    def load_theme(self, path: Union[str, Path], *, base: str = ...) -> None: ...
    def list_windows(self) -> List[Dict[str, Any]]: ...
    def close_window(self, window: Union[Window, int]) -> bool: ...
    def focus_window(self, window: Union[Window, int]) -> bool: ...
    def move_window(self, window: Union[Window, int], x: int, y: int) -> bool: ...
    def resize_window(self, window: Union[Window, int], width: int, height: int) -> bool: ...
    def set_title(self, window: Union[Window, int], title: str) -> bool: ...
    def set_property(self, cid: str, name: str, value: Any) -> None: ...
    def get_property(self, cid: str, name: str) -> Any: ...

def register_all_runtime_components() -> None: ...
def Button(*, label: str, on_click: Optional[Callback] = ..., enabled: Optional[bool] = ..., disabled: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def Text(text: str, *, selectable: Optional[bool] = ..., clipboard: Optional[str] = ..., cid: Optional[str] = ...) -> Component: ...
def Label(text: str, *, enabled: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def TextBox(*, title: str, text: str = ..., placeholder: Optional[str] = ..., clipboard: Optional[str] = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., on_submit: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def TextArea(*, title: str, text: str = ..., height: int = ..., enter_submits: bool = ..., placeholder: Optional[str] = ..., clipboard: Optional[str] = ..., kill_ring: Optional[str] = ..., history: Optional[Sequence[str]] = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., on_submit: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def Checkbox(*, label: str, checked: bool = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def RadioGroup(*, label: str, options: Sequence[str], selection: int = ..., height: Optional[int] = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def Slider(*, value: float, min: float = ..., max: float = ..., step: float = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def Spinner(text: str = ..., *, running: bool = ..., enabled: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def ProgressBar(*, value: float, min: float = ..., max: float = ..., show_text: bool = ..., text: Optional[str] = ..., enabled: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def ListBox(*, title: str, items: Sequence[str], selection: int = ..., height: Optional[int] = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def TableView(*, title: str, headers: Sequence[str], rows: Sequence[Sequence[str]], selection: int = ..., height: Optional[int] = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def VStack(*, children: Sequence[Component], spacing: int = ..., padding: Optional[PaddingLike] = ..., scrollable: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def HStack(*, children: Sequence[Component], spacing: int = ..., padding: Optional[PaddingLike] = ..., scrollable: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def Grid(*, children: Sequence[Component], columns: int = ..., row_gap: int = ..., column_gap: int = ..., padding: Optional[PaddingLike] = ..., scrollable: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def Border(child: Component, *, border: bool = ..., cid: Optional[str] = ...) -> Component: ...
def Visibility(child: Component, *, visible: bool = ..., cid: Optional[str] = ...) -> Component: ...
def Divider(orientation: str = ..., *, cid: Optional[str] = ...) -> Component: ...
def Spacer(*, cid: Optional[str] = ...) -> Component: ...
def Splitter(first: Component, second: Component, *, orientation: str = ..., split_pos: Optional[int] = ..., min_first: Optional[int] = ..., min_second: Optional[int] = ..., border: Optional[bool] = ..., cid: Optional[str] = ...) -> Component: ...
def TabView(*, tabs: Optional[Sequence[Union[Component, Tuple[str, Component]]]] = ..., children: Optional[Sequence[Component]] = ..., selection: int = ..., header_position: str = ..., on_change: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def StyledLabel(text: str, *, enabled: Optional[bool] = ..., on_link: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def Disclosure(*, title: str, content: Optional[str] = ..., children: Optional[Sequence[Component]] = ..., expanded: bool = ..., status: str = ..., enabled: Optional[bool] = ..., on_toggle: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def TypeAhead(*, title: str, items: Sequence[str], query: str = ..., selection: int = ..., accepted: str = ..., open: bool = ..., open_on_empty: bool = ..., placeholder: Optional[str] = ..., height: int = ..., max_results: int = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., on_accept: Optional[Callback] = ..., on_close: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def CommandPalette(*, items: Sequence[str], title: str = ..., query: str = ..., selection: int = ..., accepted: str = ..., open: bool = ..., open_on_empty: bool = ..., placeholder: Optional[str] = ..., height: int = ..., max_results: int = ..., enabled: Optional[bool] = ..., on_change: Optional[Callback] = ..., on_accept: Optional[Callback] = ..., on_close: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def MarkdownViewer(markdown: str, *, wrap_width: Optional[int] = ..., show_markers: Optional[bool] = ..., vertical_scrollbar: Optional[str] = ..., code_block_max_height: Optional[int] = ..., table_max_height: Optional[int] = ..., on_link: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def TerminalEmulator(*, command: Optional[str] = ..., args: Optional[Sequence[str]] = ..., scrollback_len: Optional[int] = ..., capture: Optional[bool] = ..., capture_on_click: Optional[bool] = ..., scroll_step: Optional[int] = ..., on_input: Optional[Callback] = ..., on_close: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def FileTreeNode(node_id: int, name: str, *, kind: Optional[str] = ..., children: Optional[Sequence[Dict[str, Any]]] = ..., expanded: bool = ...) -> Dict[str, Any]: ...
def FileTree(*, title: str, nodes: Sequence[Dict[str, Any]], selection: Optional[int] = ..., height: Optional[int] = ..., enabled: Optional[bool] = ..., on_select: Optional[Callback] = ..., on_rename: Optional[Callback] = ..., on_delete: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def ChatTextMessage(message_id: int, markdown: str, *, sender: str = ..., status: str = ..., timestamp: Optional[str] = ...) -> Dict[str, Any]: ...
def ChatFileMessage(message_id: int, name: str, *, url: Optional[str] = ..., sender: str = ..., status: str = ..., timestamp: Optional[str] = ...) -> Dict[str, Any]: ...
def ChatToolCallMessage(message_id: int, name: str, *, output: str = ..., tool_status: str = ..., sender: str = ..., status: str = ..., timestamp: Optional[str] = ...) -> Dict[str, Any]: ...
def ChatArtifactMessage(message_id: int, *, kind: str, anchor: Union[int, str], title: str, sender: str = ..., status: str = ..., timestamp: Optional[str] = ...) -> Dict[str, Any]: ...
def ChatMessageList(*, messages: Sequence[Dict[str, Any]], spacing: Optional[int] = ..., padding: Optional[PaddingLike] = ..., wrap_width: Optional[int] = ..., show_timestamps: Optional[bool] = ..., auto_scroll: Optional[bool] = ..., on_load_more: Optional[Callback] = ..., on_open_artifact: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
def ChatInputMode(mode: str = ..., *, title: str = ..., prompt: Optional[str] = ..., placeholder: Optional[str] = ..., height: Optional[int] = ..., options: Optional[Sequence[str]] = ..., allow_custom: Optional[bool] = ..., submit_label: Optional[str] = ..., yes_label: Optional[str] = ..., no_label: Optional[str] = ...) -> Dict[str, Any]: ...
def ChatInputPanel(*, mode: Optional[Dict[str, Any]] = ..., draft: str = ..., custom: str = ..., history: Optional[Sequence[str]] = ..., selection: int = ..., enabled: bool = ..., clear_on_submit: bool = ..., on_submit: Optional[Callback] = ..., cid: Optional[str] = ...) -> Component: ...
