from __future__ import annotations

from typing import Any, Dict, List, Sequence, Tuple, Union

RectLike = Union[Tuple[int, int, int, int], List[int], Dict[str, int]]

class AppHost:
    def __init__(self, cols: int = ..., rows: int = ..., headless: bool = ...) -> None: ...
    def add_dynamic_window(self, title: str, rect: RectLike, root: Dict[str, Any]) -> int: ...
    def apply_tree_ops(self, window_id: int, ops: Union[Dict[str, Any], Sequence[Dict[str, Any]]]) -> bool: ...
    def step(self) -> bool: ...
    def run(self) -> None: ...
    def drain_callbacks(self) -> List[Dict[str, Any]]: ...
    def send_event(self, window_id: int, event: Union[str, Dict[str, Any]]) -> Dict[str, Any]: ...
    def close_window(self, window_id: int) -> bool: ...
    def focus_window(self, window_id: int) -> bool: ...
    def move_window(self, window_id: int, x: int, y: int) -> bool: ...
    def resize_window(self, window_id: int, width: int, height: int) -> bool: ...
    def list_windows(self) -> List[Dict[str, Any]]: ...
    def set_title(self, window_id: int, title: str) -> bool: ...
    def set_property(self, id: str, name: str, value: Any) -> None: ...
    def get_property(self, id: str, name: str) -> Any: ...
    def snapshot(self) -> Dict[str, Any]: ...
    def set_theme(self, name: str) -> None: ...
    def load_theme(self, path: str, base: str = ...) -> None: ...
    def schemas(self) -> List[Dict[str, Any]]: ...

def register_all_runtime_components() -> None: ...
